# Box Muller Method:

# Have two separate standard uniform random variables U_1 and U_2.
# This is for generating two independent standard normally distributed random variables.
# Reference: Financial Mathematics: A Comprehensive Treatment By Giuseppe Campolieti and Roman Makarov

library(ggplot2)

# Hi there. In this post, I present the Box-Muller method with the statistical programming language R. 
# This topic is a bit technical but I find it interesting. 
# 
# It would be best if the reader is familiar with uniform random variables and normal random variables. 
# 
# ### Introduction
# ---
#   
# The Box-Muller method is part of a class of Monte Carlo simulation methods. Statistical simulations 
# and random number generations are useful 
# for simulating events versus waiting for the random events to occur. 
# Monte Carlo methods in general do have applications in finance 
# (i.e. Stock Markets, financial stress tests and so on). 
# One should be **VERY** careful with such simulations as context is important 
# on top of the math and stats. You would not want to simulate/generate random 
# measurements for a patient's height and weight.
# 
# ### The Box-Muller Method
# ---
# 
# This method is interesting in the sense that two independent standard normal random variables are 
# generated without the use of normal random variables. (Recall that standard normal random variables 
# have a mean of 0 and a variance of 1.) 
# These two independent standard normal random variables are generated by two independent 
# uniform random variables. 
# 
# Denote these uniform random variables as U_1 and U_2. The two independent standard 
# normal random variables are Z_1 and Z_2
# 
# 


# ### R Code
# ---

# Box Muller Method:

# Have two separate standard uniform random variables U_1 and U_2.
# This is for generating two independent standard normally distributed random variables.

library(ggplot2)

set.seed(7) 

# Generate two standard normals of size 10000 each from two std. uniform rvs:

unif1 <- runif(n = 10000, min = 0, max = 1)

unif2 <- runif(n = 10000, min = 0, max = 1)

# Generate two ind. std. normal rvs from uniforms:

z1 <- sqrt(-2*log(unif1))*(cos(2*pi*unif2))

z2<-  sqrt(-2*log(unif1))*(sin(2*pi*unif2))

# Put Results into a table:

results_tbl <- data.frame(cbind(z1, z2))

# Preview table:

head(results_tbl)
str(results_tbl)
summary(results_tbl)

# Two dimensions Plot:

ggplot(data = results_tbl, aes(x = z1, y = z2)) +
  geom_point(color = "darkgreen", size = 2) +
  geom_hline(yintercept = 0, col = "black") +
  geom_vline(xintercept = 0, col = "black") +
  labs(x = "\n z1", y = "z2 \n", title = "Box Muller Method Results \n (n = 10000) \n") +
  theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_text(face="bold", colour="darkblue", size = 12),
        axis.title.y = element_text(face="bold", colour="darkblue", size = 12))




#-------------------------------

# Sample size of 100,000

u1 <- runif(n = 10^5, min = 0, max = 1)
  
u2 <- runif(n = 10^5, min = 0, max = 1)


z1 <- sqrt(-2*log(u1))*(cos(2*pi*u2))
  
z2<-  sqrt(-2*log(u1))*(sin(2*pi*u2))

# Put In Table:

results_tbl <- data.frame(cbind(z1, z2))

# Preview table:

head(results_tbl)
str(results_tbl)
summary(results_tbl)

# Two dim Plot:

ggplot(data = results_tbl, aes(x = z1, y = z2)) +
  geom_point(color = "darkgreen", size = 2) +
  xlim(c(-5, 5)) + ylim(c(-5, 5)) +
  geom_hline(yintercept = 0, col = "black") +
  geom_vline(xintercept = 0, col = "black") +
  labs(x = "\n z1", y = "z2 \n", title = "Box Muller Method Results \n (n = 100, 000) \n") +
  theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_text(face="bold", colour="blue", size = 12),
        axis.title.y = element_text(face="bold", colour="blue", size = 12))







